# Generated by Django 2.0.7 on 2019-10-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_m22'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='m22',
            name='no_hrs',
        ),
    ]
