# Generated by Django 2.0.7 on 2019-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_remove_m22_no_hrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='m22',
            name='no_hrs',
            field=models.CharField(blank=True, db_column='NO_HRS', max_length=4, null=True),
        ),
    ]
