# Generated by Django 2.0.7 on 2019-10-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_m22_no_hrs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M22',
        ),
    ]
